apiVersion: v2
name: moon-prism-power
description: Moon Prism Power is a command-line utility for comparing and migrating anime and manga libraries from AniList to MyAnimeList.
type: application
version: 0.1.0
appVersion: "latest"
