schedule: "0 3 * * *"
timeZone: America/Fortaleza

migration:
  autoConfirm: true

reports:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: ""

secrets:
  application:
    name: moon-prism-power
    externalSecret:
      enabled: false
      storeName: vault
      refreshInterval: 1h
      remoteKey: antimeta
