{{- if .Values.secrets.application.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "secrets.application.name is required" .Values.secrets.application.name | quote }}
spec:
  refreshInterval: {{ .Values.secrets.application.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "secrets.application.externalSecret.storeName is required" .Values.secrets.application.externalSecret.storeName | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ required "secrets.application.name is required" .Values.secrets.application.name | quote }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ required "secrets.application.externalSecret.remoteKey is required" .Values.secrets.application.externalSecret.remoteKey | quote }}
{{- end }}
